In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 6.1 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
     |████████████████████████████████| 347 kB 13.8 MB/s eta 0:00:01
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 19.8 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 48.6 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.4
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/pavani/Documents/Numphyninja_assignments/Team3_PyCoders_PythonHackathon_SEP2026/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install numpy

Requirement already satisfied: numpy in ./.venv/lib/python3.9/site-packages (2.0.2)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/pavani/Documents/Numphyninja_assignments/Team3_PyCoders_PythonHackathon_SEP2026/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [6]:
%pip install nbformat

Collecting nbformat
  Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 1.6 MB/s eta 0:00:01
Collecting jsonschema>=2.6
  Downloading jsonschema-4.25.1-py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 6.5 MB/s eta 0:00:011
Requirement already satisfied: traitlets>=5.1 in ./.venv/lib/python3.9/site-packages (from nbformat) (5.15.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in ./.venv/lib/python3.9/site-packages (from nbformat) (5.8.1)
Collecting fastjsonschema>=2.15
  Downloading fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.27.1-cp39-cp39-macosx_11_0_arm64.whl (354 kB)
     |████████████████████████████████| 354 kB 9.4 MB/s eta 0:00:01
Collecting referencing>=0.28.4
  Downloading referencing-0.36.2-py3-none-any.whl (26 kB)
Collecting attrs>=22.2.0
  Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 16.4 MB/s eta 0:00:01
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.9/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.4.0)
Requirement already satisfied: typing-extensions>=4.4.0 in ./.venv/lib/python3.9/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.16.0)
Installing collected packages: rpds-py, attrs, referencing, jsonschema-specifications, jsonschema, fastjsonschema, nbformat
Successfully installed attrs-26.1.0 fastjsonschema-2.21.2 jsonschema-4.25.1 jsonschema-specifications-2025.9.1 nbformat-5.10.4 referencing-0.36.2 rpds-py-0.27.1
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/pavani/Documents/Numphyninja_assignments/Team3_PyCoders_PythonHackathon_SEP2026/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [7]:
%pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     |████████████████████████████████| 294 kB 7.3 MB/s eta 0:00:01
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in ./.venv/lib/python3.9/site-packages (from seaborn) (3.9.4)
Requirement already satisfied: pandas>=1.2 in ./.venv/lib/python3.9/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./.venv/lib/python3.9/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.2)
Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: zipp>=3.1.0 in ./.venv/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.1)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas>=1.2->seaborn) (2026.3.post1)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/pavani/Documents/Numphyninja_assignments/Team3_PyCoders_PythonHackathon_SEP2026/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [8]:
%pip install matplotlib

Requirement already satisfied: matplotlib in ./.venv/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.9/site-packages (from matplotlib) (2.0.2)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.9/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in ./.venv/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.9/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.9/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.9/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.9/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: zipp>=3.1.0 in ./.venv/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.1)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/pavani/Documents/Numphyninja_assignments/Team3_PyCoders_PythonHackathon_SEP2026/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/pavani/Documents/Python_Hackathon_Sep_2026/cardiac_failure/demography.csv")

print(df.shape)
display(df.head())
display(df.info())
# Then:

display(df.describe(include="all").T)

(2009, 7)

   inpatient_number  gender  weight  height        bmi     occupation agecat
0                 5     NaN     NaN     NaN  46.000000            NaN    NaN
1            827040  Female    50.0    1.45  23.781213            NaN  69-79
2            857781    Male    50.0    1.64  18.590125  UrbanResident  69-79
3            743087  Female    51.0    1.63  19.195303  UrbanResident  69-79
4            866418    Male    70.0    1.70  24.221453         farmer  59-69

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2009 entries, 0 to 2008
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   inpatient_number  2009 non-null   int64
 1   gender            2008 non-null   object
 2   weight            2008 non-null   float64
 3   height            2008 non-null   float64
 4   bmi               2009 non-null   float64
 5   occupation        1981 non-null   object
 6   agecat            2008 non-null   object
dtypes: float64(3), int64(1), object(3)
memory usage: 110.0+ KB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
inpatient_number,2009.0,NaN,NaN,NaN,797350.458437,44804.294546,5.0,763040.0,798725.0,829366.0,905720.0
gender,2008,2,Female,1163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weight,2008.0,NaN,NaN,NaN,52.483715,10.895935,0.0,45.0,50.0,60.0,115.0
height,2008.0,NaN,NaN,NaN,1.567869,0.096138,0.35,1.5,1.56,1.62,1.83
bmi,2009.0,NaN,NaN,NaN,21.803448,13.652299,0.0,18.491124,20.761246,23.4375,404.081633
occupation,1981,5,UrbanResident,1670,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agecat,2008,8,69-79,715,NaN,NaN,NaN,NaN,NaN,NaN,NaN